modLoader="javafml"
loaderVersion="[33,)" 
issueTrackerURL="https://github.com/TeamFelnull/IamMusicPlayer/issues"
logoFile="logo.png" 
license="LGPL v3"
[[mods]]
modId="iammusicplayer"
version="${file.jarVersion}" 
displayName="Iam Music Player"
updateJSONURL="https://raw.githubusercontent.com/TeamFelnull/IamMusicPlayer/master/version_check.json" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/iammusicplayer" 
credits="TeamFelNull(MG8853,nin8995,miyabi0333,okayu),People who contributed to the production"
authors="MORIMORI0317" 
description="Thank you for downloading!\nThis mod is The Ikisugi Music Player MOD."

[[dependencies.iammusicplayer]]
    modId="otyacraftengine"
    mandatory=true
    versionRange="[1.23,)"
    ordering="NONE"
    side="BOTH"
